# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /hestia

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

ARG APP_VERSION
RUN sed -i "s/APP_VERSION = ''/APP_VERSION = '$APP_VERSION'/g" hestia.py

ENTRYPOINT python3 bot.py
# CMD ["python3", "bot.py"]
